import pyautogui
import time


# pyautogui.press('win')
# time.sleep(3)
# pyautogui.write('chrome')
# time.sleep(3)
# pyautogui.press('enter')
# time.sleep(3)
# pyautogui.write('youtube.com')
# pyautogui.press('enter')

time.sleep(3)
pyautogui.click(x=1804, y=20)
time.sleep(2)
pyautogui.doubleClick(x=38, y=961)
time.sleep(2)
pyautogui.click(x=432, y=71)
time.sleep(1)
pyautogui.write('www.to.senac.br')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.click(x=220, y=740)
time.sleep(1)
pyautogui.click(x=214, y=808)
time.sleep(1)
pyautogui.click(x=402, y=739)
time.sleep(1)
pyautogui.click(x=378, y=556)
time.sleep(1)
pyautogui.click(x=513, y=745)
time.sleep(1)
